import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
const root = process.cwd();
const read = path => JSON.parse(readFileSync(resolve(root, path), "utf8"));
const run = (command, args) => execFileSync(command, args, { cwd: root, encoding: "utf8", stdio: ["ignore", "pipe", "pipe"] }).trim();
const baseline = read("planning/phase-g/PROTECTED-WORK-BASELINE.json");
const currentStatus = run("git", ["status", "--porcelain=v1"]);
const currentPaths = new Set(currentStatus.split("\n").filter(Boolean).map(line => line.slice(3)));
const missingBaselinePaths = (baseline.changed_files || []).filter(path => !currentPaths.has(path));
const plan = read("planning/phase-g/SELECTIVE-PROJECTION-PLAN.json");
const validation = read("planning/phase-g/PHASE-G-VALIDATION.json");
validation.protected_work = { baseline: "planning/phase-g/PROTECTED-WORK-BASELINE.json", baseline_head: baseline.head, current_head: run("git", ["rev-parse", "HEAD"]), baseline_paths_missing: missingBaselinePaths, external_worktrees_mutated: false, external_mutations: 0 };
validation.checks.protected_paths_preserved = missingBaselinePaths.length === 0;
const failed = ["event_present", "canonical_entities_resolved", "affected_routes_deterministic", "projection_manifest_hashes", "unaffected_files_identified", "protected_paths_preserved"].some(key => validation.checks[key] === false) || ["duplicate_file_ids", "duplicate_symbol_ids", "external_mutations"].some(key => Number(validation.checks[key] || 0) > 0);
validation.status = failed ? "BLOCKED" : "PARTIALLY_COMPLETE";
writeFileSync(resolve(root, "planning/phase-g/PHASE-G-VALIDATION.json"), JSON.stringify(validation, null, 2) + "\n");
const phases = read("planning/PHASE-INDEX.json");
const phaseRecord = { phase: "phase-g", status: validation.status, started: baseline.captured_at, completed: new Date().toISOString(), commit: baseline.head, predecessor: "phase-f", successor: "phase-h-or-g-remediation", files_changed: ["planning/pages/build-public.mjs", "planning/phase-g/build-selective-projection.mjs"], artifacts: ["planning/phase-g/PROJECTION-MANIFEST.json", "planning/phase-g/SELECTIVE-PROJECTION-PLAN.json", "planning/phase-g/SYNC-RECEIPT.json", "planning/phase-g/PHASE-G-VALIDATION.json", "planning/phase-g/PHASE-G-SUMMARY.json"], reports: ["planning/phase-g/PHASE-G-REPORT.md"], tests: ["node --check planning/pages/build-public.mjs", "node --check planning/phase-g/build-selective-projection.mjs", "node planning/pages/validate-public.mjs"], validation: ["planning/phase-g/PHASE-G-VALIDATION.json"], blockers: validation.blockers || [], unknowns: validation.unknowns || [], affected_entities: plan.affected_entity_ids, affected_routes: plan.affected_routes, affected_github_objects: [], affected_repositories: ["Alot1z/Ix-findings"], full_rebuild: false, sync_information: { source: "LOCAL_CANONICAL_PROJECTION", external_mutations: 0 } };
phases.phases = [...(phases.phases || []).filter(item => item.phase !== "phase-g"), phaseRecord].sort((a, b) => a.phase.localeCompare(b.phase));
phases.generated_at = new Date().toISOString();
writeFileSync(resolve(root, "planning/PHASE-INDEX.json"), JSON.stringify(phases, null, 2) + "\n");
const state = read("planning/CURRENT-STATE.json");
state.generated_at = new Date().toISOString();
state.current_phase = "G";
state.current_status = validation.status;
state.current_commit = run("git", ["rev-parse", "HEAD"]);
state.current_branch = run("git", ["branch", "--show-current"]);
state.current_validation_status = validation.status;
state.current_blockers = validation.blockers || [];
state.current_unknowns = validation.unknowns || [];
state.next_phase = validation.status === "BLOCKED" ? "G_REMEDIATION" : "H_OR_G_REMEDIATION";
state.source_authority = { external_github: "GITHUB", local_analysis: "IX-FINDINGS", external_mutations: 0 };
writeFileSync(resolve(root, "planning/CURRENT-STATE.json"), JSON.stringify(state, null, 2) + "\n");
const summary = read("planning/phase-g/PHASE-G-SUMMARY.json");
summary.status = validation.status;
summary.next_phase = state.next_phase;
summary.protected_work = validation.protected_work;
writeFileSync(resolve(root, "planning/phase-g/PHASE-G-SUMMARY.json"), JSON.stringify(summary, null, 2) + "\n");
console.log(JSON.stringify({ phase: "G", status: validation.status, baseline_paths_missing: missingBaselinePaths.length, external_mutations: 0, next_phase: state.next_phase }, null, 2));
if (validation.status === "BLOCKED") process.exit(1);
