import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
const root = process.cwd();
const read = path => JSON.parse(readFileSync(resolve(root, path), "utf8"));
const run = (command, args) => execFileSync(command, args, { cwd: root, encoding: "utf8", stdio: ["ignore", "pipe", "pipe"] }).trim();
const validation = read("planning/phase-i/PHASE-I-VALIDATION.json");
const baseline = read("planning/phase-i/PROTECTED-WORK-BASELINE.json");
const status = run("git", ["status", "--porcelain=v1"]);
const currentPaths = new Set(status.split("\n").filter(Boolean).map(line => line.slice(3)));
const missing = (baseline.changed_files || []).filter(path => !currentPaths.has(path));
validation.checks.protected_paths_preserved = missing.length === 0;
validation.protected_work = { baseline: "planning/phase-i/PROTECTED-WORK-BASELINE.json", baseline_head: baseline.head, current_head: run("git", ["rev-parse", "HEAD"]), baseline_paths_missing: missing, external_mutations: 0 };
validation.status = Object.entries(validation.checks).some(([key, value]) => ["no_absolute_paths", "source_analysis_separated", "record_ids_unique", "postings_resolve", "protected_paths_preserved"].includes(key) && value === false) || validation.checks.external_mutations > 0 ? "BLOCKED" : "PARTIALLY_COMPLETE";
writeFileSync(resolve(root, "planning/phase-i/PHASE-I-VALIDATION.json"), JSON.stringify(validation, null, 2) + "\n");
const phaseIndex = read("planning/PHASE-INDEX.json");
const record = { phase: "phase-i", status: validation.status, started: baseline.captured_at, completed: new Date().toISOString(), commit: baseline.head, predecessor: "phase-h", successor: "phase-j-or-i-remediation", files_changed: ["planning/phase-i/build-search-index.mjs", "planning/phase-i/search-knowledge.mjs"], artifacts: ["planning/phase-i/SEARCH-INDEX.json", "planning/phase-i/SEARCH-SAMPLE.json", "planning/phase-i/SEARCH-PR393-SAMPLE.json", "planning/phase-i/PHASE-I-VALIDATION.json", "planning/phase-i/PHASE-I-SUMMARY.json"], reports: ["planning/phase-i/PHASE-I-REPORT.md"], tests: ["node --check planning/phase-i/build-search-index.mjs", "node --check planning/phase-i/search-knowledge.mjs", "Phase E and PR #393 search queries"], validation: ["planning/phase-i/PHASE-I-VALIDATION.json"], blockers: validation.blockers, unknowns: validation.unknowns, affected_entities: ["search-index", "file-records", "symbol-records", "report-records", "github-source-records"], affected_routes: [], affected_github_objects: [], affected_repositories: ["Alot1z/Ix-findings"], full_rebuild: false, sync_information: { source: "LOCAL_CANONICAL_INDEXES", external_mutations: 0 } };
phaseIndex.phases = [...(phaseIndex.phases || []).filter(item => item.phase !== "phase-i"), record].sort((a, b) => a.phase.localeCompare(b.phase));
phaseIndex.generated_at = record.completed;
writeFileSync(resolve(root, "planning/PHASE-INDEX.json"), JSON.stringify(phaseIndex, null, 2) + "\n");
const state = read("planning/CURRENT-STATE.json");
Object.assign(state, { generated_at: record.completed, current_phase: "I", current_status: validation.status, current_commit: run("git", ["rev-parse", "HEAD"]), current_branch: run("git", ["branch", "--show-current"]), current_validation_status: validation.status, current_blockers: validation.blockers, current_unknowns: validation.unknowns, next_phase: "J_OR_I_REMEDIATION" });
writeFileSync(resolve(root, "planning/CURRENT-STATE.json"), JSON.stringify(state, null, 2) + "\n");
console.log(JSON.stringify({ phase: "I", status: validation.status, baseline_paths_missing: missing.length, external_mutations: 0, next_phase: state.next_phase }, null, 2));
if (validation.status === "BLOCKED") process.exit(1);
