// Generates planning/wiki/data/data.js from the canonical knowledge layer.
// Run from workspace root: node planning/wiki/build-data.mjs
// The adapter preserves the existing window.IX_DATA contract; the UI is unchanged.
import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { createLegacyUiData } from "../../knowledge/ui-compat-adapter.mjs";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "../..");
const outDir = join(here, "data");
mkdirSync(outDir, { recursive: true });

const data = createLegacyUiData(root);
const js = `// GENERATED by build-data.mjs through knowledge/ui-compat-adapter.mjs — do not edit by hand.
// Source: canonical knowledge/entities.json + relationships.json.
window.IX_DATA = ${JSON.stringify(data, null, 2)};`;

writeFileSync(join(outDir, "data.js"), js, "utf8");
console.log(`Wrote planning/wiki/data/data.js (${js.length} bytes, ${data.meta.entityCounts.graphNodes} nodes, ${data.meta.entityCounts.findings} findings)`);
