// Generates planning/wiki/data/data.js from the machine-readable planning
// registries (findings/evidence/suggestions/decisions + maps). Run from anywhere:
//   node planning/wiki/build-data.mjs
// Output: planning/wiki/data/data.js sets window.IX_DATA. Works over file:// .
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, ".."); // planning/
const outDir = join(here, "data");
mkdirSync(outDir, { recursive: true });

const read = (p) => JSON.parse(readFileSync(p, "utf8"));

const data = {
  meta: {
    title: "Ix / Compass Investigation",
    generated: "2026-08-10",
    phase: "FINAL",
    note: "Derived from planning/ registries. Evidence classes: A=source, B=artifact/runtime, C=reconstruction, D=inference.",
  },
  findings: read(join(root, "findings/registry.json")).findings,
  evidence: read(join(root, "evidence/registry.json")).evidence,
  suggestions: read(join(root, "suggestions/registry.json")).suggestions,
  decisions: read(join(root, "decisions/registry.json")).decisions,
  phases: read(join(root, "maps/phases.json")).phases,
  timeline: read(join(root, "maps/timeline-map.json")).events,
  graph: {
    nodes: read(join(root, "maps/investigation-map.json")).nodes,
    edges: read(join(root, "maps/investigation-map.json")).edges,
  },
  maps: {
    repository: read(join(root, "maps/repository-map.json")),
    evidence: read(join(root, "maps/evidence-map.json")),
    finding: read(join(root, "maps/finding-map.json")),
    dependency: read(join(root, "maps/dependency-map.json")),
    decision: read(join(root, "maps/decision-map.json")),
  },
};

const js = `// GENERATED by build-data.mjs — do not edit by hand.
// Source: planning/ registries + maps (machine-readable knowledge base).
window.IX_DATA = ${JSON.stringify(data, null, 2)};`;

writeFileSync(join(outDir, "data.js"), js, "utf8");
console.log("Wrote planning/wiki/data/data.js (" + js.length + " bytes)");